<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-02-2015 10:02:22 
* Descripcion : formEditCuentaCorriente.phtml
* ---------------------------------------
*/

/*prefijo: CTACT debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("CTACTACT");
    
$found = Obj::run()->cuentaCorrienteController->findCuentaCorriente();

?>
<form id="<?php echo CTACT; ?>formEditCuentaCorriente" name="<?php echo CTACT; ?>formEditCuentaCorriente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CTACT_5?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo BANK_3; ?></label>
                        <div class="col col-8">
                            <label class="select state-disabled"> 
                                <?php
                                    $data = Obj::run()->cuentaCorrienteController->getBancos();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>CTACT.'lst_banco',
                                            'name'=>CTACT.'lst_banco',
                                            'disabled'=>true
                                        ),
                                        'etiqueta'=>'banco',
                                        'value'=>'id_banco',
                                        'defaultEtiqueta'=>$found['id_banco'],
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CTACT_3; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo CTACT; ?>txt_cuentacorriente" name="<?php echo CTACT; ?>txt_cuentacorriente" value="<?php echo $found['cuentacorriente']?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CTACT_4; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo CTACT; ?>chk_activo" id="<?php echo CTACT; ?>chk_activo" value="A" <?php echo ($found['estado'] == 'A')?'checked':'' ?> ></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo CTACT; ?>btnEdCuentaCorriente" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CTACT; ?>formEditCuentaCorriente");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo CTACT; ?>formEditCuentaCorriente").validate({
    // Rules for form validation
    rules : {
        <?php echo CTACT; ?>txt_campo : {
            required : true,
            minlength: 3
        }
    },

    // Msn para validacion -- es opcional -- se puede eliminar, validate tiene los msn configurados por defecto
    messages : {
        <?php echo CTACT; ?>txt_campo : {
            required : "Campo requerido",
            regular: "No se permite caracteres inválidos"
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        cuentaCorriente.postEditCuentaCorriente();
    }   
});
</script>
</form>