<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-02-2015 10:02:22 
* Descripcion : indexCuentaCorriente.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("CTACTNEW");
$eliminar = Session::getPermiso("CTACTDE");
    
echo Functions::widgetOpen(array(
        "id"=>CTACT,
        "title"=>CTACT_1
    )); 
?>
<div id="<?php echo CTACT; ?>gridCuentaCorriente_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo CTACT; ?>btnNewCuentaCorriente" type="button" onclick="cuentaCorriente.getFormNewCuentaCorriente(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo CTACT; ?>gridCuentaCorriente" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.CTACT+"gridCuentaCorriente_tools",
    typeElement: "button"
});      
</script>