<?php
/*
 * ---------------------------------------
 * --------- CREATED BY CREATOR ----------
 * fecha: 07-06-2015 19:06:09 
 * Descripcion : indexAsistenciaAutomatica.phtml
 * ---------------------------------------
 */

echo Functions::widgetOpen(array(
    "id" => ASAUT,
    "title" => ASAUT_1
));
?>
<div class="widget-body-toolbar">
    <div style="position: absolute;left: 10px;top:4px" class="col-md-10">
        <div style="position: absolute;left: 10px;top:4px" class="col-md-10">
            <form id="<?php echo ASAUT; ?>formNewAsistenciaAutomatica" name="<?php echo ASAUT; ?>formNewAsistenciaAutomatica">
                <label class="col-md-2 control-label" style="padding-top: 6px">&nbsp;</label>
                <div class="col-md-5">
                    <label class="input"> 
                        <input type="text" id="<?php echo ASAUT; ?>txt_codDetectado" name="<?php echo ASAUT; ?>txt_codDetectado" onkeyup="AsistenciaAutomatica.postNewAsistenciaAutomatica();" >
                        <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo ASAUT; ?></b>
                    </label>   
                </div>
            </form>

        </div>
    </div>
</div>

<script>
    simpleScript.noSubmit('#<?php echo ASAUT; ?>formNewAsistenciaAutomatica');
</script>    