<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 15-06-2015 20:06:41 
* Descripcion : indexTipoProcesoPlanilla.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("GTPPNEW");
$eliminar = Session::getPermiso("GTPPDE");
    
echo Functions::widgetOpen(array(
        "id"=>GTPP,
        "title"=>"TipoProcesoPlanilla"
    )); 
?>
<div id="<?php echo GTPP; ?>gridTipoProcesoPlanilla_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo GTPP; ?>btnNewTipoProcesoPlanilla" type="button" onclick="TipoProcesoPlanilla.getFormNewTipoProcesoPlanilla(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo GTPP; ?>gridTipoProcesoPlanilla" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.GTPP+"gridTipoProcesoPlanilla_tools",
    typeElement: "button"
});      
</script>