<form id="<?php echo EMPL; ?>formDatosBancarios" name="<?php echo EMPL; ?>formDatosBancarios">
    <section>
        <div class="row">
            <label class="label col col-4"><?php echo EMPL_54; ?></label>
            <div class="col col-6">
                <label class="select">  
                    <?php
                        $data = Obj::run()->EmpleadosController->getBancos();

                        echo Functions::selectHtml(array(
                            'data'=>$data,
                            'atributes'=>array(
                                'id'=>EMPL.'lst_bancohaberes',
                                'name'=>EMPL.'lst_bancohaberes',
                                'onchange'=>'Empleados.getCuentaCorriente(this.value,\'H\');'
                            ),
                            'etiqueta'=>'banco',
                            'value'=>'id_banco',
                            'defaultEtiqueta'=>$found['bancoH'],
                            'txtSelect'=>true
                        ));
                    ?>
                    <div class="obligar"></div>
                </label>
            </div>
        </div>
    </section>
    <section>
        <div class="row">
            <label class="label col col-4"><?php echo EMPL_55; ?></label>
            <div class="col col-6">
                <label class="select" id="<?php echo EMPL; ?>d_ctacteH">  
                    <?php
                        $data = Obj::run()->EmpleadosController->getCuentaCorriente($found['bancoH']);

                        echo Functions::selectHtml(array(
                            'data'=>$data,
                            'atributes'=>array(
                                'id'=>EMPL.'lst_ctacteH',
                                'name'=>EMPL.'lst_ctacteH'
                            ),
                            'etiqueta'=>'cuentacorriente',
                            'value'=>'id_cuentacorriente',
                            'defaultEtiqueta'=>$found['id_cuentacorrienteH'],
                            'txtSelect'=>true
                        ));
                    ?>
                    <div class="obligar"></div>
                </label>
            </div>
        </div>
    </section>
    <section>
        <div class="row">
            <label class="label col col-4"><?php echo EMPL_56; ?></label>
            <div class="col col-6">
                <label class="select">  
                    <?php
                        $data = Obj::run()->EmpleadosController->getBancos();

                        echo Functions::selectHtml(array(
                            'data'=>$data,
                            'atributes'=>array(
                                'id'=>EMPL.'lst_bancocts',
                                'name'=>EMPL.'lst_bancocts',
                                'onchange'=>'Empleados.getCuentaCorriente(this.value,\'CTS\');'
                            ),
                            'etiqueta'=>'banco',
                            'value'=>'id_banco',
                            'defaultEtiqueta'=>$found['bancoCTS'],
                            'txtSelect'=>true
                        ));
                    ?>
                </label>
            </div>
        </div>
    </section>
    <section>
        <div class="row">
            <label class="label col col-4"><?php echo EMPL_55; ?></label>
            <div class="col col-6">
                <label class="select" id="<?php echo EMPL; ?>d_ctacteCTS">  
                    <?php
                        $data = Obj::run()->EmpleadosController->getCuentaCorriente($found['bancoCTS']);

                        echo Functions::selectHtml(array(
                            'data'=>$data,
                            'atributes'=>array(
                                'id'=>EMPL.'lst_ctacteCTS',
                                'name'=>EMPL.'lst_ctacteCTS'
                            ),
                            'etiqueta'=>'cuentacorriente',
                            'value'=>'id_cuentacorriente',
                            'defaultEtiqueta'=>$found['id_cuentacorrienteCTS'],
                            'txtSelect'=>true
                        ));
                    ?>
                </label>
            </div>
        </div>
    </section>
    <footer>
        <?php if($editar["permiso"]):?>
        <button id="<?php echo EMPL; ?>btnGrBanco" type="submit" class="<?php echo $editar["theme"]; ?>">
            <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
        </button>
        <?php endif; ?>
    </footer>
    <?php if(!$editar["permiso"]): ?>
    <script>
        simpleScript.noSubmit("#<?php echo EMPL; ?>formDatosBancarios");
    </script>
    <?php endif; ?>
    <script>
        /*configurar validacion de formulario -- este codigo es de ejemplo*/
        $("#<?php echo EMPL; ?>formDatosBancarios").validate({
            // Rules for form validation
            rules : {
                <?php echo EMPL; ?>lst_bancohaberes : {
                    required : true
                },
                <?php echo EMPL; ?>lst_ctacteH : {
                    required : true
                }
            },

            // No cambie el código de abajo
            errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
            },

            submitHandler: function(){
                Empleados.postDatosBancarios();
            }   
        });                                 
    </script>
</form>