<?php

$editar = Session::getPermiso("EMPLGR");
$nuevo  = Session::getPermiso("EMPLNEW");

$found = Obj::run()->EmpleadosController->findDatos();

?>
<div id="<?php echo EMPL; ?>formDatosLaborales" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 60%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo EMPL_45?><span id="name-empelado"></span></h4>
            </div>
            <div class="modal-body">
                
                
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#<?php echo EMPL; ?>dh1" data-toggle="tab"><?php echo EMPL_46; ?></a>
                    </li>
                    <li>
                        <a href="#<?php echo EMPL; ?>dbk" data-toggle="tab" ><?php echo EMPL_53; ?></a>
                    </li>
                    <li>
                        <a href="#<?php echo EMPL; ?>dsp" data-toggle="tab" ><?php echo EMPL_57; ?></a>
                    </li>
                    <li>
                        <a href="#<?php echo EMPL; ?>dh2" data-toggle="tab" ><?php echo EMPL_50; ?></a>
                    </li>
                    <li>
                        <a href="#<?php echo EMPL; ?>dh3" data-toggle="tab" ><?php echo EMPL_52; ?></a>
                    </li>
                </ul>
                
                <div class="tab-content padding-10">
                    <!-- ==================================INICO TAB DATOS DH=========================== -->
                    <div class="tab-pane active smart-form" id="<?php echo EMPL; ?>dh1">
                        <?php require_once (ROOT . 'modules' . DS . 'personal' . DS . 'views' . DS . 'Empleados' . DS . 'formDatos.phtml');?>
                    </div>
                    <!-- ==================================INICO TAB DATOS BANCARIOS=========================== -->
                    <div class="tab-pane smart-form" id="<?php echo EMPL; ?>dbk">
                        <?php require_once (ROOT . 'modules' . DS . 'personal' . DS . 'views' . DS . 'Empleados' . DS . 'formDatosBancarios.phtml');?>
                    </div>
                    <!-- ==================================FIN DATOS BANCARIOS=========================== -->
                    <!-- ==================================INICO TAB SISTEMA DE PENSIONES=========================== -->
                    <div class="tab-pane smart-form" id="<?php echo EMPL; ?>dsp">
                        <?php require_once (ROOT . 'modules' . DS . 'personal' . DS . 'views' . DS . 'Empleados' . DS . 'formPensiones.phtml');?>
                    </div>
                    <!-- ==================================FIN SISTEMA DE PENSIONES=========================== -->
                    <!-- ==================================INICO CARGOS=========================== -->
                    <div class="tab-pane fade" id="<?php echo EMPL; ?>dh2">
                        <div id="<?php echo EMPL; ?>gridCargos_btns">
                            <?php if($nuevo["permiso"]):?>
                            <button type="button" class="<?php echo $nuevo["theme"]; ?>" onclick="Empleados.getFormNewCargo(this);">
                                <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                            </button>
                            <?php endif; ?>
                        </div>
                        <!--<div id="<?php echo EMPL; ?>contGridCargo">-->
                            <table id="<?php echo EMPL; ?>gridCargos" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
                        <!--</div>-->
                    </div>
                    <!-- ==================================INICO CARGOS=========================== -->
                    <!-- ==================================INICO PLANILLA=========================== -->
                    <div class="tab-pane active smart-form" id="<?php echo EMPL; ?>dh3">
                        <form id="<?php echo EMPL; ?>formPlanilla" name="<?php echo EMPL; ?>formPlanilla">
                        
                        </form>
                    </div>
                    <!-- ==================================fin PLANILLA=========================== -->
                </div>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>                
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo EMPL; ?>formCargos");
</script>
<?php endif; ?>
</div>