<?php

$editar = Session::getPermiso("EMPLGR");

?>
<form id="<?php echo EMPL; ?>formNewDerechoHabientes" name="<?php echo EMPL; ?>formNewDerechoHabientes" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 80%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo EMPL_33?><span id="name-empelado"></span></h4>
            </div>
            <div class="modal-body">
                
                
                <ul class="nav nav-tabs">
                    <li class="active" id="<?php echo EMPL; ?>dp">
                        <a href="#<?php echo EMPL; ?>dh1" data-toggle="tab"><?php echo EMPL_34; ?></a>
                    </li>
                    <li>
                        <a href="#<?php echo EMPL; ?>dh2" data-toggle="tab" onclick="Empleados.getGridDerechohabientes(true);"><?php echo EMPL_35; ?></a>
                    </li>
                </ul>
                
                <div class="tab-content padding-10">
                    <!-- ==================================INICO TAB DATOS DH=========================== -->
                    <div class="tab-pane active smart-form" id="<?php echo EMPL; ?>dh1">
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_36; ?></label>
                                <div class="col col-4">
                                    <label class="select">  
                                        <?php
                                            $data = Obj::run()->EmpleadosController->getTipoVinculoFamiliar();

                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>EMPL.'lst_tiovinculofamiliar',
                                                    'name'=>EMPL.'lst_tiovinculofamiliar'
                                                ),
                                                'etiqueta'=>'vinculofamiliar',
                                                'value'=>'id_tipovinculofamiliar',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_31; ?></label>
                                <div class="col col-4">
                                    <label class="select"> 
                                        <?php
                                            $data = Obj::run()->EmpleadosController->getTipoDocumento();

                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>EMPL.'lst_tipodoc',
                                                    'name'=>EMPL.'lst_tipodoc'
                                                ),
                                                'etiqueta'=>'tipodocumentoidentidad',
                                                'value'=>'id_tipodocumentoidentidad',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_21; ?></label>
                                <div class="col col-4">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_numdocumento" name="<?php echo EMPL; ?>txt_numdocumento" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_41; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_37; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_nombres" name="<?php echo EMPL; ?>txt_nombres" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_38; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_39; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_apellidos" name="<?php echo EMPL; ?>txt_apellidos" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_40; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_12; ?></label>
                                <div class="inline-group col col-9">
                                    <label class="radio"> 
                                        <input name="<?php echo EMPL; ?>chk_sexo" id="<?php echo EMPL; ?>chk_sexoM" checked type="radio" value="M">
                                        <i></i><?php echo EMPL_13; ?>
                                    </label>
                                    <label class="radio"> 
                                        <input name="<?php echo EMPL; ?>chk_sexo" id="<?php echo EMPL; ?>chk_sexoF" type="radio" value="F">
                                        <i></i><?php echo EMPL_14; ?>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_17; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_email" name="<?php echo EMPL; ?>txt_email" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_42; ?></b>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_19; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_telefono" name="<?php echo EMPL; ?>txt_telefono" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_43; ?></b>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <fieldset>
                                    <legend><?php echo EMPL_26?></legend>
                                    <section>
                                        <div class="row">
                                            <label class="label col col-2"><?php echo EMPL_27; ?></label>
                                            <div class="col col-4">
                                                <label class="select"> 
                                                    <?php
                                                        $datadepa = Obj::run()->EmpleadosController->getDepartamento();
                                                        echo Functions::selectHtml(array(
                                                            'data'=>$datadepa,
                                                            'atributes'=>array(
                                                                'id'=>EMPL.'lst_departamentodh',
                                                                'name'=>EMPL.'lst_departamentodh',
                                                                'onchange'=>'Empleados.getProvincia(this.value,\'dh\');'
                                                            ),
                                                            'etiqueta'=>'departamento',
                                                            'value'=>'id_departamento',
                                                            'defaultEtiqueta'=>'',
                                                            'txtSelect'=>true
                                                        ));
                                                    ?><i></i>
                                                    <div class="obligar"></div>
                                                </label>
                                            </div>
                                        </div>
                                    </section>
                                    <section>
                                        <div class="row">
                                            <label class="label col col-2"><?php echo EMPL_28; ?></label>
                                            <div class="col col-4">
                                                <label class="select" id="<?php echo EMPL ?>d_provinciadh"> 
                                                    <select id="<?php echo EMPL ?>lst_provinciadh" name="<?php echo EMPL ?>lst_provinciadh">
                                                        <option value="">Seleccionar</option>
                                                    </select><i></i>
                                                    <div class="obligar"></div>
                                                </label>
                                            </div>
                                        </div>
                                    </section>
                                    <section>
                                        <div class="row">
                                            <label class="label col col-2"><?php echo EMPL_29; ?></label>
                                            <div class="col col-4">
                                                <label class="select" id="<?php echo EMPL ?>d_ubigeodh"> 
                                                    <select id="<?php echo EMPL ?>lst_ubigeodh" name="<?php echo EMPL ?>lst_ubigeodh">
                                                        <option value="">Seleccionar</option>
                                                    </select><i></i>
                                                    <div class="obligar"></div>
                                                </label>
                                            </div>
                                        </div>
                                    </section>
                                    <section>
                                        <div class="row">
                                            <label class="label col col-2"><?php echo EMPL_15; ?></label>
                                            <div class="col col-9">
                                                <label class="textarea">                                 
                                                    <i class="icon-append fa fa-question-circle"></i>
                                                    <textarea rows="3" id="<?php echo EMPL; ?>txt_direccion" name="<?php echo EMPL; ?>txt_direccion" ></textarea>
                                                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_44; ?></b>
                                                    <div class="obligar"></div>
                                                </label>
                                            </div>
                                        </div>
                                    </section>
                                </fieldset>
                            </div>
                        </section>
                    </div>
                    <!-- ==================================INICO TAB DATOS DH=========================== -->
                    <!-- ==================================INICO TAB LISTADO=========================== -->
                    <div class="tab-pane fade" id="<?php echo EMPL; ?>dh2">
                        <table id="<?php echo EMPL; ?>gridDerechoHabientes" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
                    </div>
                    <!-- ==================================INICO TAB LISTADO=========================== -->
                </div>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo EMPL; ?>btnGrDH" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo EMPL; ?>formNewDerechoHabientes");
</script>
<?php endif; ?>
<script>
    simpleScript.removeAttr.click({
        container: "#"+tabs.EMPL+"formNewDerechoHabientes",
        typeElement: "a"
    });  
                        
    simpleScript.setEvent.date({
        element: '#<?php echo EMPL; ?>txt_fechanacimiento'
    });
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo EMPL; ?>formNewDerechoHabientes").validate({
    // Rules for form validation
    rules : {
        <?php echo EMPL; ?>lst_tiovinculofamiliar : {
            required : true
        },
        <?php echo EMPL; ?>lst_tipodoc : {
            required : true
        },
        <?php echo EMPL; ?>txt_numdocumento : {
            required : true,
            number: true
        },
        <?php echo EMPL; ?>txt_nombres : {
            required : true,
            minlength: 3
        },
        <?php echo EMPL; ?>txt_apellidos : {
            required : true,
            minlength: 3
        },        
        <?php echo EMPL; ?>txt_email : {
            email: true
        },
        <?php echo EMPL; ?>lst_departamentodh : {
            required : true
        },
        <?php echo EMPL; ?>lst_provinciadh : {
            required : true
        },
        <?php echo EMPL; ?>lst_ubigeodh : {
            required : true
        },
        <?php echo EMPL; ?>txt_direccion : {
            required : true,
            minlength: 3
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        Empleados.postNewDerechoHabiente();
    }   
});
</script>
</form>