<div id="<?php echo EMPL; ?>formPlanilla">
    <section>
        <div class="row">
            <!--DATOS DE ALTA-->
            <div class="col col-6">
                <form id="<?php echo EMPL; ?>formAlta" name="<?php echo EMPL; ?>formAlta">
                    <fieldset>
                        <legend><?php echo EMPL_67?></legend>
                        <section>
                            <div class="row">
                                <label class="label col col-4"><?php echo EMPL_66; ?></label>
                                <div class="col col-6">
                                    <label class="input"> 
                                        <i class="icon-append fa fa-calendar"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_fechaingreso" name="<?php echo EMPL; ?>txt_fechaingreso" value="<?php echo $found['fecha_alta']?>">
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-4"><?php echo TPLL_4; ?></label>
                                <div class="col col-6">
                                    <label class="select"> 
                                        <?php
                                            $datadepa = Obj::run()->EmpleadosController->getTipoPlanilla();

                                            echo Functions::selectHtml(array(
                                                'data'=>$datadepa,
                                                'atributes'=>array(
                                                    'id'=>EMPL.'lst_tipoplanilla',
                                                    'name'=>EMPL.'lst_tipoplanilla'
                                                ),
                                                'etiqueta'=>'tipoplanilla',
                                                'value'=>'id_tipoplanilla',
                                                'defaultEtiqueta'=>$found['id_tipoplanilla'],
                                                'txtSelect'=>true
                                            ));
                                        ?>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section class="hide">
                            <div class="row">
                                <label class="label col col-4"><?php echo EMPL_69; ?></label>
                                <div class="col col-6">
                                    <label class="input"> 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_remuneracion" name="<?php echo EMPL; ?>txt_remuneracion" value="<?php echo $found['sueldo']?>">
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_70; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                    </fieldset>
                    <div class="modal-footer">
                        <?php if($editar["permiso"]):?>
                        <button id="<?php echo EMPL; ?>btnGrAlta" type="submit" class="<?php echo $editar["theme"]; ?>" style="padding: 5px">
                            <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                        </button>
                        <?php endif; ?>
                    </div>
                </form>                
            </div>
            <!--DATOS DE BAJA-->
            <div class="col col-6">
                <form id="<?php echo EMPL; ?>formBaja" name="<?php echo EMPL; ?>formBaja">
                    <fieldset>
                        <legend><?php echo EMPL_68?></legend>
                        <section>
                            <div class="row">
                                <label class="label col col-4"><?php echo EMPL_72; ?></label>
                                <div class="col col-6">
                                    <label class="select"> 
                                        <?php
                                            $datadepa = Obj::run()->EmpleadosController->getMotivoBaja();

                                            echo Functions::selectHtml(array(
                                                'data'=>$datadepa,
                                                'atributes'=>array(
                                                    'id'=>EMPL.'lst_motivobaja',
                                                    'name'=>EMPL.'lst_motivobaja'
                                                ),
                                                'etiqueta'=>'motivobaja',
                                                'value'=>'id_motivobaja',
                                                'defaultEtiqueta'=>$found['id_motivobaja'],
                                                'txtSelect'=>true
                                            ));
                                        ?>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-4"><?php echo EMPL_71; ?></label>
                                <div class="col col-6">
                                    <label class="input"> 
                                        <i class="icon-append fa fa-calendar"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_fechabaja" name="<?php echo EMPL; ?>txt_fechabaja" value="<?php echo $found['fecha_baja']?>">
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section class="hide">
                            <div class="row">
                                <label class="label col col-4"></label>
                                <div class="col col-6">
                                    <label class="input" style="padding: 19px"> 
                                      
                                    </label>
                                </div>
                            </div>
                        </section>
                    </fieldset>
                    <div class="modal-footer">
                        <?php if($editar["permiso"]):?>
                        <button id="<?php echo EMPL; ?>btnGrBaja" type="submit" class="<?php echo $editar["theme"]; ?>" style="padding: 5px">
                            <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                        </button>
                        <?php endif; ?>
                    </div>
                </form>
                
            </div>
        </div>
    </section>
    
    
    <?php if(!$editar["permiso"]): ?>
    <script>
        simpleScript.noSubmit("#<?php echo EMPL; ?>formAlta");
        simpleScript.noSubmit("#<?php echo EMPL; ?>formBaja");
    </script>
    <?php endif; ?>
    
    <script>
        simpleScript.setEvent.date({element: '#'+tabs.EMPL+'txt_fechaingreso'})
        simpleScript.setEvent.date({element: '#'+tabs.EMPL+'txt_fechabaja'})
        
        /*configurar validacion de formulario -- este codigo es de ejemplo*/
        $("#<?php echo EMPL; ?>formAlta").validate({
            // Rules for form validation
            rules : {
                <?php echo EMPL; ?>txt_fechaingreso : {
                    required : true,
                    date: true
                },
                <?php echo EMPL; ?>lst_tipoplanilla : {
                    required : true
                },
                <?php echo EMPL; ?>txt_remuneracion : {
                    number: true
                }
            },

            // No cambie el código de abajo
            errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
            },

            submitHandler: function(){
                Empleados.postAlta();
            }   
        });     
        
        $("#<?php echo EMPL; ?>formBaja").validate({
            // Rules for form validation
            rules : {
                <?php echo EMPL; ?>lst_motivobaja : {
                    required : true
                },
                <?php echo EMPL; ?>txt_fechabaja : {
                    required : true,
                    date: true
                }                
            },

            // No cambie el código de abajo
            errorPlacement : function(error, element) {
                error.insertAfter(element.parent());
            },

            submitHandler: function(){
                Empleados.postBaja();
            }   
        }); 
    </script>
</div>