<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-03-2015 23:03:01 
* Descripcion : formNewEmpleados.phtml
* ---------------------------------------
*/

/*prefijo: EMPL debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("EMPLGR");
    
?>
<form id="<?php echo EMPL; ?>formNewEmpleados" name="<?php echo EMPL; ?>formNewEmpleados" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 80%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo EMPL_2?></h4>
            </div>
            <div class="modal-body smart-form"> 
                
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#<?php echo EMPL; ?>iss1" data-toggle="tab"><?php echo EMPL_3; ?></a>
                    </li>
                    <li class="">
                        <a href="#<?php echo EMPL; ?>iss2" data-toggle="tab"><?php echo EMPL_23; ?></a>
                    </li>
                    <li class="hide">
                        <a href="#<?php echo EMPL; ?>iss3" data-toggle="tab"><?php echo EMPL_3; ?></a>
                    </li>
                    <li class="hide">
                        <a href="#<?php echo EMPL; ?>iss4" data-toggle="tab"><?php echo EMPL_3; ?></a>
                    </li>
                </ul>
                <div class="tab-content padding-10">
                    <!-- ==================================INICO TAB DATOS GENERALES=========================== -->
                    <div class="tab-pane active" id="<?php echo EMPL; ?>iss1">
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_4; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_primernombre" name="<?php echo EMPL; ?>txt_primernombre" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_5; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_6; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_segundonombre" name="<?php echo EMPL; ?>txt_segundonombre" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_7; ?></b>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_8; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_apellidopaterno" name="<?php echo EMPL; ?>txt_apellidopaterno" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_9; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_10; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_apellidomaterno" name="<?php echo EMPL; ?>txt_apellidomaterno" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_11; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_12; ?></label>
                                <div class="inline-group col col-9">
                                    <label class="radio"> 
                                        <input name="<?php echo EMPL; ?>chk_sexo" id="<?php echo EMPL; ?>chk_sexoH" checked type="radio" value="M">
                                        <i></i><?php echo EMPL_13; ?>
                                    </label>
                                    <label class="radio"> 
                                        <input name="<?php echo EMPL; ?>chk_sexo" id="<?php echo EMPL; ?>chk_sexoM" type="radio" value="F">
                                        <i></i><?php echo EMPL_14; ?>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_15; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_direccion" name="<?php echo EMPL; ?>txt_direccion" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_16; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_17; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_email" name="<?php echo EMPL; ?>txt_email" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_18; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_19; ?></label>
                                <div class="col col-9">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_telefono" name="<?php echo EMPL; ?>txt_telefono" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_20; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_21; ?></label>
                                <div class="col col-3">
                                    <label class="select"> 
                                        <?php
                                            $data = Obj::run()->EmpleadosController->getTipoDocumento();

                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>EMPL.'lst_clasificador',
                                                    'name'=>EMPL.'lst_clasificador'
                                                ),
                                                'etiqueta'=>'tipodocumentoidentidad',
                                                'value'=>'id_tipodocumentoidentidad',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_21; ?></label>
                                <div class="col col-3">
                                    <label class="input">                                 
                                        <i class="icon-append fa fa-question-circle"></i>
                                        <input type="text" id="<?php echo EMPL; ?>txt_numdocumento" name="<?php echo EMPL; ?>txt_numdocumento" >
                                        <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo EMPL_22; ?></b>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                        <section>
                            <div class="row">
                                <div class="col col-6">
                                    <fieldset>
                                        <legend><?php echo EMPL_25?></legend>
                                        <section>
                                            <div class="row">
                                                <label class="label col col-4"><?php echo EMPL_27; ?></label>
                                                <div class="col col-6">
                                                    <label class="select"> 
                                                        <?php
                                                            $data = Obj::run()->EmpleadosController->getDepartamento();

                                                            echo Functions::selectHtml(array(
                                                                'data'=>$data,
                                                                'atributes'=>array(
                                                                    'id'=>EMPL.'lst_clasificador',
                                                                    'name'=>EMPL.'lst_clasificador'
                                                                ),
                                                                'etiqueta'=>'departamento',
                                                                'value'=>'id_departamento',
                                                                'defaultEtiqueta'=>'',
                                                                'txtSelect'=>true
                                                            ));
                                                        ?><i></i>
                                                        <div class="obligar"></div>
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                        <section>
                                            <div class="row">
                                                <label class="label col col-4"><?php echo EMPL_28; ?></label>
                                                <div class="col col-6">
                                                    <label class="select"> 
                                                        <select id="<?php echo EMPL ?>lst_provincia" name="<?php echo EMPL ?>lst_provincia">
                                                            <option value="">Seleccionar</option>
                                                        </select><i></i>
                                                        <div class="obligar"></div>
                                                    </label>
                                                </div>
                                            </div>
                                        </section>
                                    </fieldset>
                                </div>
                                <div class="col col-6">
                                    <fieldset>
                                        <legend><?php echo EMPL_26?></legend>
                                    </fieldset>
                                </div>
                            </div>
                        </section>
                    </div>
                    <!-- ==================================FIN TAB DATOS GENERALES=========================== -->
                    
                    <!-- ==================================INICO TAB DATOS LABORALES=========================== -->
                    <div class="tab-pane fade" id="<?php echo EMPL; ?>iss2">
                        <section>
                            <div class="row">
                                <label class="label col col-2"><?php echo EMPL_24; ?></label>
                                <div class="col col-9">
                                    <label class="select">  
                                        <?php
                                            $data = Obj::run()->EmpleadosController->getActividad();

                                            echo Functions::selectHtml(array(
                                                'data'=>$data,
                                                'atributes'=>array(
                                                    'id'=>EMPL.'lst_actividad',
                                                    'name'=>EMPL.'lst_actividad'
                                                ),
                                                'etiqueta'=>'actividad',
                                                'value'=>'id_actividad',
                                                'defaultEtiqueta'=>'',
                                                'txtSelect'=>true
                                            ));
                                        ?><i></i>
                                        <div class="obligar"></div>
                                    </label>
                                </div>
                            </div>
                        </section>
                    </div>
                    <!-- ==================================INICO TAB DATOS LABORALES=========================== -->
                </div>
                
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo EMPL; ?>btnGrEmpleados" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo EMPL; ?>formNewEmpleados");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo EMPL; ?>formNewEmpleados").validate({
    // Rules for form validation
    rules : {
        <?php echo EMPL; ?>txt_campo : {
            required : true,
            minlength: 3
        }
    },

    // Msn para validacion -- es opcional -- se puede eliminar, validate tiene los msn configurados por defecto
    messages : {
        <?php echo EMPL; ?>txt_campo : {
            required : "Campo requerido",
            regular: "No se permite caracteres inválidos"
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        Empleados.postNewEmpleados();
    }   
});
</script>
</form>