<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-03-2015 23:03:01 
* Descripcion : indexEmpleados.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("EMPLNEW");
$eliminar = Session::getPermiso("EMPLDE");
    
echo Functions::widgetOpen(array(
        "id"=>EMPL,
        "title"=>EMPL_1
    )); 
?>
<div id="<?php echo EMPL; ?>gridEmpleados_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo EMPL; ?>btnNewEmpleados" type="button" onclick="Empleados.getFormNewEmpleados(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo EMPL; ?>gridEmpleados" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.EMPL+"gridEmpleados_tools",
    typeElement: "button"
});      
</script>