<?php
/*
 * ---------------------------------------
 * --------- CREATED BY CREATOR ----------
 * fecha: 22-03-2015 01:03:50 
 * Descripcion : indexEstructuraOrganica.phtml
 * ---------------------------------------
 */
$nuevo = Session::getPermiso("ESOGGR");
$eliminar = Session::getPermiso("ESOGDE");

echo Functions::widgetOpen(array(
    "id" => ESOG,
    "title" => ESOG_1
));
?>
<br>
<form id="<?php echo ESOG ?>formIndex" name="<?php echo ESOG ?>formIndex" class="form-horizontal">
    <section>
        <div class="form-group">
            <label class="col-md-2 control-label"><?php echo ESOG_1; ?></label>
            <div class="col-md-8">
                <input class="form-control" type="text" id="<?php echo ESOG; ?>txt_estructuraorg" name="<?php echo ESOG; ?>txt_estructuraorg">
            </div>
        </div>
    </section> 
    <section>
        <div class="form-group">
            <label class="col-md-2 control-label"></label>
            <div class="col-md-2">
                <?php if ($nuevo["permiso"]): ?>
                    <button id="<?php echo ESOG; ?>btnGrEstructuraOrganica" type="submit" class="<?php echo $nuevo["theme"]; ?>">
                        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
                    </button>
                <?php endif; ?>
            </div>
        </div>
    </section> 
</form>
<section>
    <div id="<?php echo ESOG; ?>basicdiagram" style="width: 100%; height: 480px; border-style: dotted; border-width: 1px;" />
</section>

<?php echo Functions::widgetClose(); ?>
<script>
    simpleScript.removeAttr.click({
        container: "#" + tabs.ESOG + "formIndex",
        typeElement: "button"
    });
    $("#<?php echo ESOG; ?>formIndex").validate({
        // Rules for form validation
        rules: {
                <?php echo ESOG; ?>txt_estructuraorg: {
                        required: true
                    }
                },
                // No cambie el código de abajo
                errorPlacement: function (error, element) {
                    error.insertAfter(element.parent());
                },
                submitHandler: function () {
                    EstructuraOrganica.postNewEstructuraOrganica(1,'formIndex');
                }
            });
</script>