<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 10-04-2015 17:04:02 
* Descripcion : formNewGenerarContrato.phtml
* ---------------------------------------
*/

/*prefijo: GNCTR debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("GNCTRGR");
    
?>
<form id="<?php echo GNCTR; ?>formNewGenerarContrato" name="<?php echo GNCTR; ?>formNewGenerarContrato" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 70%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php GNCTR_2?></h4>
            </div>
            <div class="modal-body"> 
                <table id="<?php echo GNCTR; ?>gridSinContrato" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo GNCTR; ?>btnGrGenerarContrato" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo GNCTR; ?>formNewGenerarContrato");
</script>
<?php endif; ?>
<script>
    simpleScript.removeAttr.click({
        container: "#"+tabs.GNCTR+"gridSinContrato_tools",
        typeElement: "button"
    }); 

/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo GNCTR; ?>formNewGenerarContrato").validate({

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        if(GenerarContratoScript.validateGrid()){
            GenerarContrato.postGenerarContrato();
        }else{
            simpleScript.notify.error({
                content: lang.GenerarContrato.VALCONT 
            });
        }
    }   
});
</script>
</form>