<form id="<?php echo GNCTR; ?>formHistorial" name="<?php echo GNCTR; ?>formHistorial" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 70%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php GNCTR_2?></h4>
            </div>
            <div class="modal-body"> 
                <table id="<?php echo GNCTR; ?>gridHistorial" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
            </div>
            <div class="modal-footer">
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<script>
    
</script>
</form>