<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 28-01-2015 00:01:08 
* Descripcion : formEditSubClasificadorDetalle.phtml
* ---------------------------------------
*/

/*prefijo: SBCLD debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("SBCLDACT");
    
$found = Obj::run()->SubClasificadorDetalleController->findSubClasificadorDetalle();

?>
<form id="<?php echo SBCLD; ?>formEditSubClasificadorDetalle" name="<?php echo SBCLD; ?>formEditSubClasificadorDetalle" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo SBCLD_5?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSF_4; ?></label>
                        <div class="col col-3">
                            <label class="input state-disabled"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo SBCLD; ?>txt_codigo" name="<?php echo SBCLD; ?>txt_codigo" value="<?php echo $found['codigo']?>" disabled>
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo SBCLD_2; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo SBCLF_2; ?></label>
                        <div class="col col-8">
                            <label class="select state-disabled"> 
                                <?php
                                    $data = Obj::run()->clasificadorDetalleController->getAllSubClasificador();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>SBCLD.'lst_subclasificador',
                                            'name'=>SBCLD.'lst_subclasificador',
                                            'disabled'=>true
                                        ),
                                        'etiqueta'=>array('codigo','subclasificador'),
                                        'value'=>'id_subclasificador',
                                        'defaultEtiqueta'=>$found['id_subclasificador'],
                                        'txtSelect'=>true
                                    ));
                                ?>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSFD_1; ?></label>
                        <div class="col col-8">
                            <label class="select state-disabled" id="cont_lst_clasificador_detalle"> 
                                <?php
                                    $datax = Obj::run()->SubClasificadorDetalleController->getAllClasificadorDetalle($found['id_subclasificador']);
                                  
                                    echo Functions::selectHtml(array(
                                        'data'=>$datax,
                                        'atributes'=>array(
                                            'id'=>SBCLD.'lst_clasificadordetalle',
                                            'name'=>SBCLD.'lst_clasificadordetalle',
                                            'disabled'=>true
                                        ),
                                        'etiqueta'=>array('codigo','clasificadordetalle'),
                                        'value'=>'id_clasificadordetalle',
                                        'defaultEtiqueta'=>$found['id_clasificadordetalle'],
                                        'txtSelect'=>true
                                    ));
                                ?>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo SBCLD_3; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo SBCLD; ?>txt_subclasificadordetalle" name="<?php echo SBCLD; ?>txt_subclasificadordetalle" value="<?php echo $found['subclasificadordetalle']?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo SBCLD_4; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo SBCLD; ?>chk_activo" id="<?php echo SBCLD; ?>chk_activo" value="A" <?php echo ($found['estado'] == 'A')?'checked':'' ?>></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo SBCLD; ?>btnEdSubClasificadorDetalle" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo SBCLD; ?>formEditSubClasificadorDetalle");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo SBCLD; ?>formEditSubClasificadorDetalle").validate({
    // Rules for form validation
    rules: {
        <?php echo SBCLD; ?>txt_codigo: {
            required: true,
            maxlength: 11
        },
        <?php echo SBCLD; ?>lst_subclasificador: {
            required: true
        },
        <?php echo SBCLD; ?>lst_clasificadordetalle: {
            required: true
        },        
        <?php echo SBCLD; ?>txt_subclasificadordetalle: {
            required: true
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        SubClasificadorDetalle.postEditSubClasificadorDetalle();
    }   
});
</script>
</form>