<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 29-03-2015 23:03:37 
* Descripcion : formEditHorario.phtml
* ---------------------------------------
*/

/*prefijo: HRIO debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("HRIOACT");
    
$found = Obj::run()->HorarioController->findHorario();

?>
<form id="<?php echo HRIO; ?>formEditHorario" name="<?php echo HRIO; ?>formEditHorario" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo HRIO_3?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo HRIO_4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo HRIO; ?>txt_horario" name="<?php echo HRIO; ?>txt_horario" value="<?php echo $found['horario']?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo HRIO_5; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo HRIO_6; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-clock-o"></i>
                                <input class="form-control clockpicker" id="<?php echo HRIO; ?>txt_maniana_in" name="<?php echo HRIO; ?>txt_maniana_in" data-autoclose="true" data-default="now" type="text" value="<?php echo $found['hora_ingreso_m']?>">
                                <div class="obligar"></div>
                            </label>
                        </div>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-clock-o"></i>
                                <input class="form-control clockpicker" id="<?php echo HRIO; ?>txt_maniana_sal" name="<?php echo HRIO; ?>txt_maniana_sal" data-autoclose="true" data-default="now" data-vibrate="true" type="text" value="<?php echo $found['hora_salida_m']?>">
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo HRIO_7; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-clock-o"></i>
                                <input class="form-control clockpicker" id="<?php echo HRIO; ?>txt_tarde_in" name="<?php echo HRIO; ?>txt_tarde_in" data-autoclose="true" data-default="now" type="text" value="<?php echo $found['hora_ingreso_t']?>">
                                <div class="obligar"></div>
                            </label>
                        </div>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-clock-o"></i>
                                <input class="form-control clockpicker" id="<?php echo HRIO; ?>txt_tarde_sal" name="<?php echo HRIO; ?>txt_tarde_sal" data-autoclose="true" data-default="now" data-vibrate="true" type="text" value="<?php echo $found['hora_salida_t']?>">
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo HRIO; ?>chk_activo" id="<?php echo HRIO; ?>chk_activo" value="A" <?php echo ($found['estado'] == 'A')?'checked':'' ?>></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo HRIO; ?>btnEdHorario" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo HRIO; ?>formEditHorario");
</script>
<?php endif; ?>
<script>
    simpleScript.setEvent.time({
        element: '.clockpicker'
    });
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo HRIO; ?>formEditHorario").validate({
    // Rules for form validation
    rules : {
        <?php echo HRIO; ?>txt_horario : {
            required : true,
            minlength: 3
        },
        <?php echo HRIO; ?>txt_maniana_in : {
            required : true,
            time: true
        },
        <?php echo HRIO; ?>txt_maniana_sal : {
            required : true,
            time: true
        },
        <?php echo HRIO; ?>txt_tarde_in : {
            required : true,
            time: true
        },
        <?php echo HRIO; ?>txt_tarde_sal : {
            required : true,
            time: true
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        Horario.postEditHorario();
    }   
});
</script>
</form>