<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 29-03-2015 23:03:37 
* Descripcion : indexHorario.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("HRIONEW");
$eliminar = Session::getPermiso("HRIODE");
    
echo Functions::widgetOpen(array(
        "id"=>HRIO,
        "title"=>HRIO_1
    )); 
?>
<div id="<?php echo HRIO; ?>gridHorario_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo HRIO; ?>btnNewHorario" type="button" onclick="Horario.getFormNewHorario(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo HRIO; ?>gridHorario" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.HRIO+"gridHorario_tools",
    typeElement: "button"
});      
</script>