<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-03-2015 16:03:35 
* Descripcion : formNewTipoDeAusencia.phtml
* ---------------------------------------
*/

/*prefijo: TAUS debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("TAUSGR");
    
?>
<form id="<?php echo TAUS; ?>formNewTipoDeAusencia" name="<?php echo TAUS; ?>formNewTipoDeAusencia" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo TAUS_2; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo TAUS_1; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo TAUS; ?>txt_tipoausencia" name="<?php echo TAUS; ?>txt_tipoausencia" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo TAUS_4; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo TAUS_5; ?></label>
                        <div class="col col-4">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo TAUS; ?>txt_grupoausencia" name="<?php echo TAUS; ?>txt_grupoausencia" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo TAUS_6; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="<?php echo TAUS; ?>chk_activo" id="<?php echo TAUS; ?>chk_activo" value="A"></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo TAUS; ?>btnGrTipoDeAusencia" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo TAUS; ?>formNewTipoDeAusencia");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo TAUS; ?>formNewTipoDeAusencia").validate({
    // Rules for form validation
    rules : {
        <?php echo TAUS; ?>txt_tipoausencia : {
            required : true,
            minlength: 3
        },
        <?php echo TAUS; ?>txt_grupoausencia : {
            required : true,
            minlength: 2
        }
    },



    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        TipoDeAusencia.postNewTipoDeAusencia();
    }   
});
</script>
</form>