<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-03-2015 16:03:35 
* Descripcion : indexTipoDeAusencia.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("TAUSNEW");
$eliminar = Session::getPermiso("TAUSDE");
    
echo Functions::widgetOpen(array(
        "id"=>TAUS,
        "title"=>TAUS_1
    )); 
?>
<div id="<?php echo TAUS; ?>gridTipoDeAusencia_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo TAUS; ?>btnNewTipoDeAusencia" type="button" onclick="TipoDeAusencia.getFormNewTipoDeAusencia(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo TAUS; ?>gridTipoDeAusencia" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.TAUS+"gridTipoDeAusencia_tools",
    typeElement: "button"
});      
</script>