<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-04-2015 22:04:14 
* Descripcion : formMeses.phtml
* ---------------------------------------
*/

/*prefijo: MSGN debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("MSGNACT");
    
$found = Obj::run()->GenerarMesController->findGenerarMes();

?>
<form id="<?php echo MSGN; ?>formMeses" name="<?php echo MSGN; ?>formMeses" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">TITULO DE FORMULARIO</h4>
            </div>
            <div class="modal-body smart-form"> 
                CONTENIDO DEL FORM (utilizar constantes en Labels.php)
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo MSGN; ?>btnEdGenerarMes" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo MSGN; ?>formMeses");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo MSGN; ?>formMeses").validate({
    // Rules for form validation
    rules : {
        <?php echo MSGN; ?>txt_campo : {
            required : true,
            minlength: 3
        }
    },

    // Msn para validacion -- es opcional -- se puede eliminar, validate tiene los msn configurados por defecto
    messages : {
        <?php echo MSGN; ?>txt_campo : {
            required : "Campo requerido",
            regular: "No se permite caracteres inválidos"
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        GenerarMes.postEditGenerarMes();
    }   
});
</script>
</form>