<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 18-04-2015 22:04:13 
* Descripcion : indexGenerarMes.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("MSGNNEW");
$eliminar = Session::getPermiso("MSGNDE");
    
echo Functions::widgetOpen(array(
        "id"=>MSGN,
        "title"=>MSGN_1,
        "width"=>"50%"
    )); 
?>
<div id="<?php echo MSGN; ?>gridGenerarMes_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo MSGN; ?>btnNewGenerarMes" type="button" onclick="GenerarMes.getFormNewGenerarMes(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo MSGN; ?>gridGenerarMes" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.MSGN+"gridGenerarMes_tools",
    typeElement: "button"
});      
</script>