<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 24-05-2015 01:05:46 
* Descripcion : indexRetencionJudicial.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("RTJDNEW");
$eliminar = Session::getPermiso("RTJDDE");
    
echo Functions::widgetOpen(array(
        "id"=>RTJD,
        "title"=>RTJD_1
    )); 
?>
<div id="<?php echo RTJD; ?>gridRetencionJudicial_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo RTJD; ?>btnNewRetencionJudicial" type="button" onclick="RetencionJudicial.getFormNewRetencionJudicial(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo RTJD; ?>gridRetencionJudicial" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.RTJD+"gridRetencionJudicial_tools",
    typeElement: "button"
});      
</script>