<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 11-03-2015 16:03:55 
* Descripcion : indexCategoriaTrabajador.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("KTRBANEW");
$eliminar = Session::getPermiso("KTRBADE");
    
echo Functions::widgetOpen(array(
        "id"=>KTRBA,
        "title"=>KTRBA_1
    )); 
?>
<div id="<?php echo KTRBA; ?>gridCategoriaTrabajador_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo KTRBA; ?>btnNewCategoriaTrabajador" type="button" onclick="CategoriaTrabajador.getFormNewCategoriaTrabajador(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo KTRBA; ?>gridCategoriaTrabajador" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.KTRBA+"gridCategoriaTrabajador_tools",
    typeElement: "button"
});      
</script>