<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-02-2015 18:02:03 
* Descripcion : indexTipoDocId.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("TDCIDNEW");
$eliminar = Session::getPermiso("TDCIDDE");
    
echo Functions::widgetOpen(array(
        "id"=>TDCID,
        "title"=>TDCID_1
    )); 
?>
<div id="<?php echo TDCID; ?>gridTipoDocId_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo TDCID; ?>btnNewTipoDocId" type="button" onclick="TipoDocId.getFormNewTipoDocId(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo TDCID; ?>gridTipoDocId" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.TDCID+"gridTipoDocId_tools",
    typeElement: "button"
});      
</script>