<?php
/*
 * ---------------------------------------
 * --------- CREATED BY CREATOR ----------
 * fecha: 22-01-2015 13:01:45 
 * Descripcion : formNewClasificador.phtml
 * ---------------------------------------
 */

/* prefijo: CLSF debe ser alias en tabla men_menuprincipal */
$grabar = Session::getPermiso("CLSFGR");
?>
<form id="<?php echo CLSF; ?>formNewClasificador" name="<?php echo CLSF; ?>formNewClasificador" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CLSF_1?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo CLSF_4; ?></label>
                        <div class="col col-3">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo CLSF; ?>txt_codigo" name="<?php echo CLSF; ?>txt_codigo" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CLSF_5; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo CLSF_2; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo CLSF; ?>txt_clasificador" name="<?php echo CLSF; ?>txt_clasificador" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CLSF_3; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"><?php echo CLSF_7; ?></label>
                        <div class="col col-3">
                            <label class="select"> 
                                <?php
                                    $data = array(
                                        array('value'=>'I','label'=>'Ingreso'),
                                        array('value'=>'G','label'=>'Gasto')
                                    );
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>CLSF.'lst_tipo',
                                            'name'=>CLSF.'lst_tipo'
                                        ),
                                        'etiqueta'=>'label',
                                        'value'=>'value',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-2"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="<?php echo CLSF; ?>chk_activo" id="<?php echo CLSF; ?>chk_activo" value="A"></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if ($grabar["permiso"]): ?>
                    <button id="<?php echo CLSF; ?>btnGrClasificador" type="submit" class="<?php echo $grabar["theme"]; ?>">
                        <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                    </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

    <!-- si no tiene permiso se anula submit desde cualquier input -->
    <?php if (!$grabar["permiso"]): ?>
        <script>
            simpleScript.noSubmit("#<?php echo CLSF; ?>formNewClasificador");
        </script>
    <?php endif; ?>
    <script>
        /*configurar validacion de formulario -- este codigo es de ejemplo*/
        $("#<?php echo CLSF; ?>formNewClasificador").validate({
            // Rules for form validation
            rules: {
                <?php echo CLSF; ?>txt_codigo: {
                    required: true,
                    number: true,
                    maxlength: 11
                },
                <?php echo CLSF; ?>txt_clasificador: {
                    required: true
                },
                <?php echo CLSF; ?>lst_tipo: {
                    required: true
                }       
            },
                   
                    // No cambie el código de abajo
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            },
            submitHandler: function () {
                clasificador.postNewClasificador();
            }
        });        
    </script>
</form>