<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 22-01-2015 13:01:45 
* Descripcion : indexClasificador.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("CLSFNEW");
$eliminar = Session::getPermiso("CLSFDE");
    
echo Functions::widgetOpen(array(
        "id"=>CLSF,
        "title"=>CLSF_2
    )); 
?>
<div id="<?php echo CLSF; ?>gridClasificador_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo CLSF; ?>btnNewClasificador" type="button" onclick="clasificador.getFormNewClasificador(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo CLSF; ?>gridClasificador" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: '#'+tabs.CLSF+'gridClasificador_tools',
    typeElement: 'button'
});      
</script>