<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 12-03-2015 08:03:42 
* Descripcion : formEditConceptoPlanilla.phtml
* ---------------------------------------
*/

/*prefijo: PCNCP debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("PCNCPACT");
    
$found = Obj::run()->ConceptoPlanillaController->findConceptoPlanilla();

?>
<form id="<?php echo PCNCP; ?>formEditConceptoPlanilla" name="<?php echo PCNCP; ?>formEditConceptoPlanilla" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo PCNCP_3 ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo PCNCP_4; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo PCNCP; ?>txt_concepto" name="<?php echo PCNCP; ?>txt_concepto" value="<?php echo $found['conceptoplanilla']?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo PCNCP_5; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo PCNCP_6; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo PCNCP; ?>txt_descorta" name="<?php echo PCNCP; ?>txt_descorta" value="<?php echo $found['descripcion_corta']?>" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo PCNCP_7; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo PCNCP_8; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = array(
                                        array('id'=>'A','value'=>'Aporte'),
                                        array('id'=>'D','value'=>'Descuento'),
                                        array('id'=>'I','value'=>'Ingreso')
                                    );
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>PCNCP.'lst_clasificacion',
                                            'name'=>PCNCP.'lst_clasificacion'
                                        ),
                                        'etiqueta'=>'value',
                                        'value'=>'id',
                                        'defaultEtiqueta'=>$found['clasificacion'],
                                        'txtSelect'=>true
                                    ));
                                ?>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo PCNCP; ?>chk_activo" id="<?php echo PCNCP; ?>chk_activo" value="A" <?php echo ($found['estado'] == 'A')?'checked':'' ?> ></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo PCNCP; ?>btnEdConceptoPlanilla" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo PCNCP; ?>formEditConceptoPlanilla");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo PCNCP; ?>formEditConceptoPlanilla").validate({
    // Rules for form validation
    rules : {
        <?php echo PCNCP; ?>txt_concepto : {
            required : true,
            minlength: 3
        },
        <?php echo PCNCP; ?>txt_descorta : {
            required : true,
            minlength: 3
        },
        <?php echo PCNCP; ?>lst_clasificacion : {
            required : true
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        ConceptoPlanilla.postEditConceptoPlanilla();
    }   
});
</script>
</form>