<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 30-03-2015 01:03:44 
* Descripcion : indexSistemaPension.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("SISPENEW");
$eliminar = Session::getPermiso("SISPEDE");
    
echo Functions::widgetOpen(array(
        "id"=>SISPE,
        "title"=>ESPE_1
    )); 
?>
<div id="<?php echo SISPE; ?>gridSistemaPension_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo SISPE; ?>btnNewSistemaPension" type="button" onclick="SistemaPension.getFormNewSistemaPension(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo SISPE; ?>gridSistemaPension" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.SISPE+"gridSistemaPension_tools",
    typeElement: "button"
});      
</script>