<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 02-04-2015 21:04:20 
* Descripcion : indexTipoPlanilla.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("TPLLNEW");
$eliminar = Session::getPermiso("TPLLDE");
    
echo Functions::widgetOpen(array(
        "id"=>TPLL,
        "title"=>TPLL_1
    )); 
?>
<div id="<?php echo TPLL; ?>gridTipoPlanilla_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo TPLL; ?>btnNewTipoPlanilla" type="button" onclick="TipoPlanilla.getFormNewTipoPlanilla(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo TPLL; ?>gridTipoPlanilla" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.TPLL+"gridTipoPlanilla_tools",
    typeElement: "button"
});      
</script>