<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 30-01-2015 12:01:46 
* Descripcion : formNewEspecifica.phtml
* ---------------------------------------
*/

/*prefijo: ESPE debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("ESPEGR");
    
?>
<form id="<?php echo ESPE; ?>formNewEspecifica" name="<?php echo ESPE; ?>formNewEspecifica" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo ESPE_1?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSF_4; ?></label>
                        <div class="col col-3">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo ESPE; ?>txt_codigo" name="<?php echo ESPE; ?>txt_codigo" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo ESPE_4; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSF_2; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = Obj::run()->EspecificaController->getAllClasificador();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>ESPE.'lst_clasificador',
                                            'name'=>ESPE.'lst_clasificador',
                                            'onchange'=>'Especifica.getSubClasificador(this.value);'
                                        ),
                                        'etiqueta'=>array('codigo','clasificador'),
                                        'value'=>'id_clasificador',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?><i></i>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo SBCLF_2; ?></label>
                        <div class="col col-8">
                            <label class="select" id="cont_subclasificador"> 
                                <select id="<?php echo ESPE; ?>lst_subclasificador" name="<?php echo ESPE; ?>lst_subclasificador">
                                    <option value=""><?php echo LBL_SELECCIONAR?></option>
                                </select><i></i>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSFD_1; ?></label>
                        <div class="col col-8">
                            <label class="select" id="cont_clasificador_detalle"> 
                                <select id="<?php echo ESPE; ?>lst_clasificadordetalle" name="<?php echo ESPE; ?>lst_clasificadordetalle">
                                    <option value=""><?php echo LBL_SELECCIONAR?></option>
                                </select><i></i>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo SBCLD_3; ?></label>
                        <div class="col col-8">
                            <label class="select" id="cont_subclasificador_detalle"> 
                                <select id="<?php echo ESPE; ?>lst_subclasificadordetalle" name="<?php echo ESPE; ?>lst_subclasificadordetalle">
                                    <option value=""><?php echo LBL_SELECCIONAR?></option>
                                </select><i></i>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo ESPE_2; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo ESPE; ?>txt_especifica" name="<?php echo ESPE; ?>txt_especifica" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo ESPE_3; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo ESPE; ?>chk_activo" id="<?php echo ESPE; ?>chk_activo" value="A" checked></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
                
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo ESPE; ?>btnGrEspecifica" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo ESPE; ?>formNewEspecifica");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo ESPE; ?>formNewEspecifica").validate({
    // Rules for form validation
    rules: {
        <?php echo ESPE; ?>txt_codigo: {
            required: true,
            maxlength: 11
        },
        <?php echo ESPE; ?>lst_clasificador: {
            required: true
        },
        <?php echo ESPE; ?>lst_subclasificador: {
            required: true
        },
        <?php echo ESPE; ?>lst_clasificadordetalle: {
            required: true
        },
        <?php echo ESPE; ?>lst_subclasificadordetalle: {
            required: true
        },
        <?php echo ESPE; ?>txt_especifica: {
            required: true
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        Especifica.postNewEspecifica();
    }   
});
</script>
</form>