<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 30-01-2015 12:01:46 
* Descripcion : indexEspecifica.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("ESPENEW");
$eliminar = Session::getPermiso("ESPEDE");
    
echo Functions::widgetOpen(array(
        "id"=>ESPE,
        "title"=>ESPE_2
    )); 
?>
<div id="<?php echo ESPE; ?>gridEspecifica_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo ESPE; ?>btnNewEspecifica" type="button" onclick="Especifica.getFormNewEspecifica(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo ESPE; ?>gridEspecifica" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.ESPE+"gridEspecifica_tools",
    typeElement: "button"
});      
</script>