<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 24-06-2015 16:06:47 
* Descripcion : indexProcesarPlanilla.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("PRPLLNEW");
$eliminar = Session::getPermiso("PRPLLDE");
    
echo Functions::widgetOpen(array(
        "id"=>PRPLL,
        "title"=>"ProcesarPlanilla"
    )); 
?>
<div id="<?php echo PRPLL; ?>gridProcesarPlanilla_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo PRPLL; ?>btnNewProcesarPlanilla" type="button" onclick="ProcesarPlanilla.getFormNewProcesarPlanilla(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo PRPLL; ?>gridProcesarPlanilla" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.PRPLL+"gridProcesarPlanilla_tools",
    typeElement: "button"
});      
</script>