<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 26-01-2015 23:01:32 
* Descripcion : formNewClasificadorDetalle.phtml
* ---------------------------------------
*/

/*prefijo: CLSFD debe ser alias en tabla men_menuprincipal*/
$grabar = Session::getPermiso("CLSFDGR");
    
?>
<form id="<?php echo CLSFD; ?>formNewClasificadorDetalle" name="<?php echo CLSFD; ?>formNewClasificadorDetalle" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo CLSFD_2; ?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSF_4; ?></label>
                        <div class="col col-3">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo CLSFD; ?>txt_codigo" name="<?php echo CLSFD; ?>txt_codigo" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CLSFD_3; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo SBCLF_2; ?></label>
                        <div class="col col-8">
                            <label class="select"> 
                                <?php
                                    $data = Obj::run()->clasificadorDetalleController->getAllSubClasificador();
                                    
                                    echo Functions::selectHtml(array(
                                        'data'=>$data,
                                        'atributes'=>array(
                                            'id'=>CLSFD.'lst_subclasificador',
                                            'name'=>CLSFD.'lst_subclasificador'
                                        ),
                                        'etiqueta'=>array('codigo','subclasificador'),
                                        'value'=>'id_subclasificador',
                                        'defaultEtiqueta'=>'',
                                        'txtSelect'=>true
                                    ));
                                ?>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo CLSFD_1; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo CLSFD; ?>txt_clasificadordetalle" name="<?php echo CLSFD; ?>txt_clasificadordetalle" >
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo CLSFD_4; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" checked="checked" name="<?php echo CLSFD; ?>chk_activo" id="<?php echo CLSFD; ?>chk_activo" value="A"></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($grabar["permiso"]):?>
                <button id="<?php echo CLSFD; ?>btnGrClasificadorDetalle" type="submit" class="<?php echo $grabar["theme"]; ?>">
                    <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$grabar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CLSFD; ?>formNewClasificadorDetalle");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo CLSFD; ?>formNewClasificadorDetalle").validate({
    // Rules for form validation
    rules: {
        <?php echo CLSFD; ?>txt_codigo: {
            required: true,
            maxlength: 11
        },
        <?php echo CLSFD; ?>lst_subclasificador: {
            required: true
        },
        <?php echo CLSFD; ?>txt_clasificadordetalle: {
            required: true
        }
    },

    // Msn para validacion -- es opcional -- se puede eliminar, validate tiene los msn configurados por defecto
    messages : {
        <?php echo CLSFD; ?>txt_campo : {
            required : "Campo requerido",
            regular: "No se permite caracteres inválidos"
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        clasificadorDetalle.postNewClasificadorDetalle();
    }   
});
</script>
</form>