<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 26-01-2015 23:01:32 
* Descripcion : indexClasificadorDetalle.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("CLSFDNEW");
$eliminar = Session::getPermiso("CLSFDDE");
    
echo Functions::widgetOpen(array(
        "id"=>CLSFD,
        "title"=>CLSFD_1
    )); 
?>
<div id="<?php echo CLSFD; ?>gridClasificadorDetalle_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo CLSFD; ?>btnNewClasificadorDetalle" type="button" onclick="clasificadorDetalle.getFormNewClasificadorDetalle(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo CLSFD; ?>gridClasificadorDetalle" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.CLSFD+"gridClasificadorDetalle_tools",
    typeElement: "button"
});      
</script>