<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 16-03-2015 22:03:56 
* Descripcion : indexTipoVinculoFamiliar.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VNFANEW");
$eliminar = Session::getPermiso("VNFADE");
    
echo Functions::widgetOpen(array(
        "id"=>VNFA,
        "title"=>VNFA_1
    )); 
?>
<div id="<?php echo VNFA; ?>gridTipoVinculoFamiliar_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo VNFA; ?>btnNewTipoVinculoFamiliar" type="button" onclick="TipoVinculoFamiliar.getFormNewTipoVinculoFamiliar(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo VNFA; ?>gridTipoVinculoFamiliar" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.VNFA+"gridTipoVinculoFamiliar_tools",
    typeElement: "button"
});      
</script>