<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 07-03-2015 16:03:00 
* Descripcion : indexCargo.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("KRGONEW");
$eliminar = Session::getPermiso("KRGODE");
    
echo Functions::widgetOpen(array(
        "id"=>KRGO,
        "title"=>KRGO_1
    )); 
?>
<div id="<?php echo KRGO; ?>gridCargo_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo KRGO; ?>btnNewCargo" type="button" onclick="Cargo.getFormNewCargo(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo KRGO; ?>gridCargo" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.KRGO+"gridCargo_tools",
    typeElement: "button"
});      
</script>