<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-02-2015 09:02:37 
* Descripcion : indexBanco.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("BANKNEW");
$eliminar = Session::getPermiso("BANKDE");
    
echo Functions::widgetOpen(array(
        "id"=>BANK,
        "title"=>BANK_1
    )); 
?>
<div id="<?php echo BANK; ?>gridBanco_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo BANK; ?>btnNewBanco" type="button" onclick="banco.getFormNewBanco(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo BANK; ?>gridBanco" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.BANK+"gridBanco_tools",
    typeElement: "button"
});      
</script>