<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 12-03-2015 16:03:52 
* Descripcion : indexActividad.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("HACTNEW");
$eliminar = Session::getPermiso("HACTDE");
    
echo Functions::widgetOpen(array(
        "id"=>HACT,
        "title"=>HACT_1
    )); 
?>
<div id="<?php echo HACT; ?>gridActividad_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo HACT; ?>btnNewActividad" type="button" onclick="Actividad.getFormNewActividad(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo HACT; ?>gridActividad" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.HACT+"gridActividad_tools",
    typeElement: "button"
});      
</script>