<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-02-2015 19:02:59 
* Descripcion : formEditTipoPago.phtml
* ---------------------------------------
*/

/*prefijo: PTPG debe ser alias en tabla men_menuprincipal*/
$editar = Session::getPermiso("PTPGACT");
    
$found = Obj::run()->TipoPagoController->findTipoPago();

?>
<form id="<?php echo PTPG; ?>formEditTipoPago" name="<?php echo PTPG; ?>formEditTipoPago" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php echo PTPG_4?></h4>
            </div>
            <div class="modal-body smart-form"> 
                <section>
                    <div class="row">
                        <label class="label col col-3"><?php echo PTPG_1; ?></label>
                        <div class="col col-8">
                            <label class="input"> 
                                <i class="icon-append fa fa-question-circle"></i>
                                <input type="text" id="<?php echo PTPG; ?>txt_tipopago" name="<?php echo PTPG; ?>txt_tipopago" value="<?php echo $found['tipopago']?>">
                                <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo PTPG_3; ?></b>
                                <div class="obligar"></div>
                            </label>
                        </div>
                    </div>
                </section>
                <section>
                    <div class="row">
                        <label class="label col col-3"></label>
                        <div class="col col-3">
                            <label class="checkbox">
                                <input type="checkbox" name="<?php echo PTPG; ?>chk_activo" id="<?php echo PTPG; ?>chk_activo" value="A" <?php echo ($found['estado'] == 'A')?'checked':'' ?> ></input>
                                <i></i>
                                <?php echo CK_ACTIVO; ?>
                            </label>
                        </div>
                    </div>
                </section>
            </div>
            <div class="modal-footer">
                <div class="foot-obligar"></div>
                <?php if($editar["permiso"]):?>
                <button id="<?php echo PTPG; ?>btnEdTipoPago" type="submit" class="<?php echo $editar["theme"]; ?>">
                    <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
                </button>
                <?php endif; ?>
                <button type="button" class="<?php echo THEME_CLOSE; ?>">
                    <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo PTPG; ?>formEditTipoPago");
</script>
<?php endif; ?>
<script>
/*configurar validacion de formulario -- este codigo es de ejemplo*/
$("#<?php echo PTPG; ?>formEditTipoPago").validate({
    // Rules for form validation
    rules : {
        <?php echo PTPG; ?>txt_tipopago : {
            required : true,
            minlength: 3
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        TipoPago.postEditTipoPago();
    }   
});
</script>
</form>