<?php


$nuevo = Session::getPermiso("VACANEW");
$grabar = Session::getPermiso("VACAGR");
$eliminar = Session::getPermiso("VACADE");

$found = Obj::run()->VacacionesController->findTrabajador();

?>
<form id="<?php echo VACA ?>formGestionar" name="<?php echo VACA ?>formGestionar" class="smart-form">
    <footer>
        <div class="foot-obligar"></div>
        <?php if ($eliminar["permiso"]): ?>
        <button id="<?php echo VACA; ?>btnELIVacaciones" type="button" class="<?php echo $eliminar["theme"]; ?>" disabled onclick="Vacaciones.postDeleteMovimiento();">
                <i class="<?php echo $eliminar["icono"]; ?>"></i> <?php echo $eliminar["accion"]; ?>
            </button>
        <?php endif; ?>
        <?php if ($grabar["permiso"]): ?>
            <button id="<?php echo VACA; ?>btnGRAVacaciones" type="submit" class="<?php echo $grabar["theme"]; ?>">
                <i class="<?php echo $grabar["icono"]; ?>"></i> <?php echo $grabar["accion"]; ?>
            </button>
        <?php endif; ?>
        <?php if ($nuevo["permiso"]): ?>
        <button id="<?php echo VACA; ?>btnNEWVacaciones" type="button" class="<?php echo $nuevo["theme"]; ?>" disabled onclick="$('#<?php echo VACA ?>formGestionar')[0].reset();$('#'+tabs.VACA+'lst_tipovac').attr('disabled',false);simpleScript.updateChosen({element:'#<?php echo VACA ?>lst_tipovac'});">
                <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
            </button>
        <?php endif; ?>
    </footer>
    <section>
        <div class="row">
            <label class="label col col-2"><?php echo VACA_8; ?></label>
            <div class="col col-8">
                <label class="input state-disabled">                                 
                    <input type="text" value="<?php echo $found["apellidopaterno"]?> <?php echo $found["apellidomaterno"]?>" disabled>
                </label>
            </div>
        </div>
    </section>
    <section>
        <div class="row">
            <label class="label col col-2"><?php echo VACA_2; ?></label>
            <div class="col col-5">
                <label class="select"> 
                    <?php
                    $data = Obj::run()->TipoDeAusenciaController->getAllTipoDeAusencia();
                    echo Functions::selectHtml(array(
                        'data' => $data,
                        'atributes' => array(
                            'id' => VACA.'lst_tipovac',
                            'name' => VACA.'lst_tipovac'
                        ),
                        'etiqueta' => array('id_tipo_ausencia', 'tipo_ausencia'),
                        'value' => 'id_tipo_ausencia',
                        'defaultEtiqueta' => '',
                        'txtSelect' => true
                    ));
                    ?>
                    <div class="obligar"></div>
                </label>
            </div>
        </div>
    </section>

    <section>
        <div class="row">
            <label class="label col col-2"><?php echo VACA_3; ?></label>
            <div class="col col-2">
                <label class="input">                                 
                    <i class="icon-append fa fa-calendar"></i>
                    <input type="text" id="<?php echo VACA; ?>txt_fechainicio" name="<?php echo VACA; ?>txt_fechainicio" onchange="$('#<?php echo VACA; ?>txt_dias').val(simpleScript.restarFechas(this.value,$('#<?php echo VACA; ?>txt_fechafin').val()))">
                    <div class="obligar"></div>
                </label>
            </div>

            <label class="label col col-1"><?php echo VACA_4; ?></label>
            <div class="col col-2">
                <label class="input">                                 
                    <i class="icon-append fa fa-calendar"></i>
                    <input type="text" id="<?php echo VACA; ?>txt_fechafin" name="<?php echo VACA; ?>txt_fechafin" onchange="$('#<?php echo VACA; ?>txt_dias').val(simpleScript.restarFechas($('#<?php echo VACA; ?>txt_fechainicio').val(),this.value))">
                    <div class="obligar"></div>
                </label>
            </div>

            <label class="label col col-1"><?php echo VACA_5; ?></label>
            <div class="col col-1">
                <label class="input"> 
                    <i class="icon-append fa fa-question-circle"></i>
                    <input type="text" id="<?php echo VACA; ?>txt_dias" name="<?php echo VACA; ?>txt_dias" onkeyup="$('#<?php echo VACA; ?>txt_fechafin').val(simpleScript.addDay($('#<?php echo VACA; ?>txt_dias').val(),$('#<?php echo VACA; ?>txt_fechainicio').val()))">
                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo KRGO_4; ?></b>
                    <div class="obligar"></div>
                </label>
            </div>
        </div>
    </section>
    <section>
        <div class="row">
            <label class="label col col-2"><?php echo VACA_6; ?></label>
            <div class="col col-2">
                <label class="input">                                 
                    <i class="icon-append fa fa-calendar"></i>
                    <input type="text" id="<?php echo VACA; ?>txt_fechaproceso" name="<?php echo VACA; ?>txt_fechaproceso" >
                </label>
            </div>
        </div>
    </section>
    <section>
        <div class="row">
            <label class="label col col-2"><?php echo VACA_7; ?></label>
            <div class="col col-5">
                <label class="input"> 
                    <i class="icon-append fa fa-question-circle"></i>
                    <input type="text" id="<?php echo VACA; ?>txt_comentario" name="<?php echo VACA; ?>txt_comentario" >
                    <b class="tooltip tooltip-top-right"><i class="fa fa-question-circle txt-color-teal"></i> <?php echo KRGO_4; ?></b>
                </label>
            </div>
        </div>
    </section>
</form>

<table id="<?php echo VACA; ?>gridGestionVacaciones" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    



<script>
    simpleScript.removeAttr.click({
        container: "#" + tabs.VACA + "formGestionar",
        typeElement: "button"
    });

    simpleScript.removeAttr.change({
        container: "#" + tabs.VACA + "formGestionar",
        typeElement: "input"
    });
    
    simpleScript.setEvent.date({
        element: '#<?php echo VACA; ?>txt_fechaproceso'
    });
    
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VACA; ?>txt_fechainicio',
        fin: '#<?php echo VACA; ?>txt_fechafin',
        opt: 'minDate'
    });
    simpleScript.setEvent.dateRange({
        ini: '#<?php echo VACA; ?>txt_fechafin',
        fin: '#<?php echo VACA; ?>txt_fechainicio',
        opt: 'maxDate'
    });
    
$("#<?php echo VACA; ?>formGestionar").validate({
    // Rules for form validation
    rules : {
        <?php echo VACA; ?>lst_tipovac : {
            required : true
        },
        <?php echo VACA; ?>txt_fechainicio : {
            required : true,
            date: true
        },
        <?php echo VACA; ?>txt_fechafin : {
            required : true,
            date: true
        },
        <?php echo VACA; ?>txt_dias : {
            required : true,
            number: true
        }
    },

    // No cambie el código de abajo
    errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
    },

    submitHandler: function(){
        Vacaciones.postGestionar();
    }   
});
</script>
