<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 05-04-2015 19:04:19 
* Descripcion : indexVacaciones.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("VACANEW");
$eliminar = Session::getPermiso("VACADE");
    
echo Functions::widgetOpen(array(
        "id"=>VACA,
        "title"=>VACA_1
    )); 
?>
<div id="<?php echo VACA; ?>gridVacaciones_btns">
    <!-- verificar permisos -->
    <?php if($nuevo["permiso"]): ?>
    <button id="<?php echo VACA; ?>btnNewVacaciones" type="button" onclick="Vacaciones.getFormNewVacaciones(this);" class="<?php echo $nuevo["theme"]; ?>">
        <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
    </button>
    <?php endif; ?>
</div>
<table id="<?php echo VACA; ?>gridVacaciones" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>    
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.VACA+"gridVacaciones_tools",
    typeElement: "button"
});      
</script>