<?php /*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 27-02-2015 23:02:52 
* Descripcion : formEditTipoContrato.phtml
* ---------------------------------------
*/

echo Functions::widgetOpen(array(
    'id' => CTPCT.'edit',
    'title' => CTPCT_4    
));
$editar = Session::getPermiso("CTPCTACT");

$found = Obj::run()->TipoContratoController->findTipoContrato();
?>
<form id="<?php echo CTPCT; ?>formEditTipoContrato" name="<?php echo CTPCT; ?>formEditTipoContrato"  >
    <div class="row" style="padding:10px;">
        
        <div class="modal-body smart-form" > 
            <section>
                <div class="row">
                    <label class="label col col-2"><?php echo CTPCT_2; ?></label>
                    <div class="col col-10">
                        <label class="input"> 
                            <i class="icon-append fa fa-keyboard-o"></i>
                            <input type="text" id="<?php echo CTPCT; ?>txt_contrato" name="<?php echo CTPCT; ?>txt_contrato" value="<?php echo $found['contrato']; ?>" >
                            <b class="tooltip tooltip-top-right"><i class="fa fa-keyboard-o txt-color-teal"></i> <?php echo CTPCT_2; ?></b>
                        </label>
                    </div>
                </div>
            </section> 
            <section>
                <div class="row">
                    <label class="label col col-2"></label>
                    <div class="col col-10">
                        <label class="checkbox">
                            <input type="checkbox" name="<?php echo CTPCT; ?>chk_activo" id="<?php echo CTPCT; ?>chk_activo" value="A" <?php echo ($found['estado'] == 'A')?'checked':'' ?> ></input>
                            <i></i>
                            <?php echo CK_ACTIVO; ?>
                        </label>
                    </div>
                </div>
            </section>
        </div>            
        <article class="col-sm-12 col-md-12 col-lg-6 sortable-grid ui-sortable" style="width: 100%; ">
<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-colorbutton="false" 
 data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-fullscreenbutton="false" data-widget-sortable="false">				
                           <header><h2><?php echo CTPCT_2; ?></h2></header>
                            <!-- widget div-->
                            <div>
                                    <!-- widget edit box -->
                                    <div class="jarviswidget-editbox">
                                            <!-- This area used as dropdown edit box -->                                                    
                                    </div>
                                    <!-- end widget edit box -->
                                    <!-- widget content -->
                                    <div class="widget-body no-padding">
                                            <div class="summernote">
                                                <?php 
                                                $html = str_replace('\\','',$found['contenido'] );
                                                echo htmlspecialchars_decode($html,ENT_QUOTES); ?>
                                            </div>						
                                            <div class="widget-footer smart-form">
                                                <div class="btn-group">
                                                        <!--
                                                        <button class="btn btn-sm btn-primary" type="button">
                                                                <i class="fa fa-times"></i> Cancel
                                                        </button>	
                                                        -->			
                                                </div>				
                                            </div>						
                                    </div>
                                    <!-- end widget content -->
                            </div>
                            <!-- end widget div -->
                    </div>	
        </article>
        <textarea id="<?php echo CTPCT; ?>txt_cuerpo" name="<?php echo CTPCT; ?>txt_cuerpo" class="hide" rows="3"></textarea>
        <div class="modal-footer">
            <div class="foot-obligar"></div>
            <?php if($editar["permiso"]):?>
            <button id="<?php echo CTPCT; ?>btnEdTipoContrato" type="submit" class="<?php echo $editar["theme"]; ?>">
                <i class="<?php echo $editar["icono"]; ?>"></i> <?php echo $editar["accion"]; ?>
            </button>
            <?php endif; ?>
            <button type="button" class="<?php echo THEME_CLOSE; ?>" onclick="simpleScript.closeTab(tabs.CTPCT+'new');" >
                <i class="<?php echo ICON_CLOSE; ?>"></i> <?php echo BTN_CLOSE; ?>
            </button>
        </div>        
    </div><!-- /.modal-dialog -->
</form>

 <?php echo Functions::widgetClose(); ?>
<!-- si no tiene permiso se anula submit desde cualquier input -->
<?php if(!$editar["permiso"]): ?>
<script>
    simpleScript.noSubmit("#<?php echo CTPCT; ?>formEditTipoContrato");
</script>
<?php endif; ?>
<script>
    loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/summernote/summernote.js", function(){
            loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/markdown/markdown.js", function(){
                            loadScript("theme/<?php echo DEFAULT_LAYOUT ?>/js/plugin/markdown/bootstrap-markdown.min.js", pagefunction);
            });
    });
    
    pageSetUp();
    var pagefunction = function() {		
            $('.summernote').summernote({
                    height : 300,
                    focus : true,
                    tabsize : 2,
                    toolbar: [
                    ['style', ['style','bold', 'italic', 'underline', 'clear']],                    
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['height', ['height']],
                    ['insert', ['picture']],
                    ['Misc',['codeview']],
                  ]
            });				
    };	
            
    
    

    /*configurar validacion de formulario -- este codigo es de ejemplo*/
    $("#<?php echo CTPCT; ?>formEditTipoContrato").validate({
        rules : {
            <?php echo CTPCT; ?>txt_contrato : {
                required : true,
                minlength: 3
            }
        },       

       
        errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
        },

        submitHandler: function(){
            $("#<?php echo CTPCT; ?>txt_cuerpo").val($('#<?php echo CTPCT; ?>formEditTipoContrato .summernote').code());
            var aHTML = $( '#'+tabs.CTPCT+'txt_cuerpo').val(); 
            
            if(aHTML.length === 52){
                simpleScript.notify.error({
                    content: lang.TipoContrato.REQCONT
                });
                return false;
            }
            TipoContrato.postEditTipoContrato();
        }   
 });
  
    $('#<?php echo CTPCT; ?>formEditTipoContrato .note-toolbar .note-help').css('display','none');  
        
</script>