<?php 
/*
* ---------------------------------------
* --------- CREATED BY CREATOR ----------
* fecha: 28-05-2015 07:05:13 
* Descripcion : indexAsistenciaManual.phtml
* ---------------------------------------
*/
$nuevo    = Session::getPermiso("ASMNNEW");
$eliminar = Session::getPermiso("ASMNDE");
$buscar   = Session::getPermiso("ASMNBS");

echo Functions::widgetOpen(array(
        "id"=>ASMN,
        "title"=>ASMN_1
    )); 
?>
<div class="widget-body-toolbar">
    <div style="position: absolute;left: 10px;top:4px" class="col-md-10">
        <label class="col-md-2 control-label" for="select-1" style="padding-top: 6px"><?php echo ASMN_2;?></label>
        <div class="col-md-5">
            <?php
            $data = Obj::run()->AsistenciaManualController->getTrabajador();

            echo Functions::selectHtml(array(
                'data' => $data,
                'atributes' => array(
                    'id' => ASMN . 'lst_trabajador',
                    'name' => ASMN . 'lst_trabajador'
                ),
                'etiqueta' => 'nombrecompleto',
                'value' => 'id_trabajador',
                'defaultEtiqueta' => '',
                'txtSelect' => true
            ));
            ?>
        </div>
        <div class="col-md-4">
            <?php if($buscar["permiso"]): ?>
            <button id="<?php echo ASMN; ?>btnBusAsistenciaManual" type="button" onclick="AsistenciaManual.getCargaAsistenciaManualGrid($('#<?php echo ASMN;?>lst_trabajador').val());" class="<?php echo $buscar["theme"]; ?>">
                <i class="<?php echo $buscar["icono"]; ?>"></i> <?php echo $buscar["accion"]; ?>
            </button>
            <?php endif; ?>
        </div>
    </div>
</div>
<div id="<?php echo ASMN; ?>contTable">
    <div id="<?php echo ASMN; ?>gridAsistenciaManual_btns" class="hide">
        <!-- verificar permisos -->
        <?php if($nuevo["permiso"]): ?>
        <button id="<?php echo ASMN; ?>btnNewAsistenciaManual" type="button" onclick="AsistenciaManual.getFormNewAsistenciaManual(this);" class="<?php echo $nuevo["theme"]; ?>">
            <i class="<?php echo $nuevo["icono"]; ?>"></i> <?php echo $nuevo["accion"]; ?>
        </button>
        <?php endif; ?>
    </div>

    <table id="<?php echo ASMN; ?>gridAsistenciaManual" class="table table-striped table-hover table-condensed dataTable table-bordered" ></table>  
</div>
<?php echo Functions::widgetClose(); ?>
<script>
simpleScript.removeAttr.click({
    container: "#"+tabs.ASMN+"gridAsistenciaManual_tools",
    typeElement: "button"
});      
</script>